pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'jenkins_sky' }
            }
            steps {
                sh 'pip --version'
            }
        }
        stage('Test') {
            agent {
                docker { image 'jenkins_sky' }
            }
            steps {
                sh 'pip --version'
            }
        }
       stage('Deploy') {
            agent {
                docker { image 'jenkins_sky' }
            }
            steps {
                sh 'pip --version'
            }
        }
        
    }
}